---
title: "Load_Dataset"
author: "massaine"
date: "2022-11-25"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Load Spectral and Phenotype data
### Data struture:
```{r, eval = F}
### Trial, plot_name, acession_name, Plot, Block, Cook15, Cook20, Cook25, Cook30, Cook40, + Spectra data

library(dplyr)
library(stringr)
Cooking_traits <- c("Cook15","Cook20","Cook25","Cook30","Cook40")
```
   
### Dados ASD
```{r, eval = F}
dados2020 <- read.table(file=here::here("data","2020-DadosNIRASD_fen_BR.PYTGS.19.txt"), header=T, sep="\t", na.strings="NA", strip.white=TRUE, check.names=FALSE)
dados2020 <- dados2020[!is.na(dados2020$`350`),]
dados2020 <- cbind(dados2020[,c("Trial","plot_name",
                                "accession_name",
                                "plot_number",
                                "block_number",
                                Cooking_traits,"Type")],
                                dados2020[21:ncol(dados2020)])


dados2021 <- read.table(file=here::here("data","2021-DadosNIRASD_Cook.txt"), header=T, sep="\t", na.strings="NA",
                        strip.white=TRUE, check.names=FALSE)
dados2021 <- cbind(dados2021[,c("Trial","plot_name",
                                "accession_name",
                                "plot_number",
                                "block_number",
                                Cooking_traits,"Type")],
                                dados2021[16:ncol(dados2021)])

dados2022<-read.table(file=here::here("data","2022_DadosNIRASD_Cook.txt"), 
                      header=T, sep="\t", na.strings="NA",
                      strip.white=TRUE, check.names=FALSE)
dados2022 <- cbind(dados2022[,c("Trial","plot_name",
                                "accession_name",
                                "plot_number",
                                "block_number",
                                Cooking_traits,"Type")],
                                dados2022[12:ncol(dados2022)])

dados <- rbind(dados2020,dados2021,dados2022)
dados <- dados[!is.na(dados$Cook15),]
dados <- dados[!is.na(dados$Cook20),]
dados <- dados[!is.na(dados$Cook25),]
dados <- dados[!is.na(dados$Cook30),]
dados <- dados[!is.na(dados$Cook40),]
dados <- droplevels(dados)

dados$Cook15 <- as.factor(dados$Cook15)
dados$Cook20 <- as.factor(dados$Cook20)
dados$Cook25 <- as.factor(dados$Cook25)
dados$Cook30 <- as.factor(dados$Cook30)
dados$Cook40 <- as.factor(dados$Cook40)

levels(dados$Cook15) <- c("No","No","Yes","Yes")
levels(dados$Cook20) <- c("No","No","Yes","Yes")
levels(dados$Cook25) <- c("No","No","Yes","Yes")
levels(dados$Cook30) <- c("No","No","Yes","Yes")
levels(dados$Cook40) <- c("No","No","Yes","Yes")
  
dados$accession_name <- as.factor(dados$accession_name)
dados$accession_name <- recode(dados$accession_name, 
                                "EucxRox" = "EucaliptoXRoxinha", 
                                "BRS-GemaOvo" = "BRS-Gema-de-Ovo",
                                "Aipim-Brasil" = "Aipim Brasil",
                                "Aipim-Abacate" = "AipimAbacate")  

dados$Type <- as.factor(dados$Type)
levels(as.factor(dados$Type))  
levels(dados$Type) <- c("Fresh Root","Mashed","Mashed")
```

### creating multi classes trait ASD
```{r, eval = F}
dados1 <- dados[,Cooking_traits]
dados1$Cook15 <- gsub("Yes","15min",dados1$Cook15)
dados1$Cook20 <- gsub("Yes","20min",dados1$Cook20)
dados1$Cook25 <- gsub("Yes","25min",dados1$Cook25)
dados1$Cook30 <- gsub("Yes","30min",dados1$Cook30)
dados1$Cook40 <- gsub("Yes","40min",dados1$Cook40)
dados1$Mult6C <- as.factor(str_c(dados1$Cook15,dados1$Cook20,dados1$Cook25,
                                 dados1$Cook30,dados1$Cook40,sep = "",
                                 collapse = NULL))
levels(dados1$Mult6C) <- c("15min","20min","25min","30min","40min","No")
dados1$Mult4C <- dados1$Mult6C
levels(dados1$Mult4C) <- c("15min","25min","25min","40min","40min","No")
dados <- cbind(dados[,1:10],dados1[,6:7],dados[,11:ncol(dados)])
```

### save data
```{r}
#save(dados, file = here::here("output", "dadosASD.RData"))
```


### Dados BUCHI
```{r, eval = F}
dados2020 <- read.table(file=here::here("data","2020-DadosNIRBUCHI_fen_PYTGS.CETBAG.19.txt"), header=T, sep="\t", na.strings="NA", strip.white=TRUE, check.names=FALSE)
dados2020 <- dados2020[!is.na(dados2020$`1000`),]
dados2020 <- cbind(dados2020[,c("Trial","plot_name",
                                "accession_name",
                                "plot_number",
                                "block_number",
                                Cooking_traits,"Type")],
                                dados2020[20:ncol(dados2020)])

dados2021 <- read.table(file=here::here("data","2021-DadosNIRBUCHI_Cook.txt"), header=T, sep="\t", na.strings="NA",
                        strip.white=TRUE, check.names=FALSE)
dados2021 <- cbind(dados2021[,c("Trial","plot_name",
                                "accession_name",
                                "plot_number",
                                "block_number",
                                Cooking_traits,"Type")],
                                dados2021[18:ncol(dados2021)])

dados2022<-read.table(file=here::here("data","2022_DadosNIRBUCHI_Cook.txt"), 
                      header=T, sep="\t", na.strings="NA",
                      strip.white=TRUE, check.names=FALSE)
dados2022 <- cbind(dados2022[,c("Trial","plot_name",
                                "accession_name",
                                "plot_number",
                                "block_number",
                                Cooking_traits,"Type")],
                                dados2022[12:ncol(dados2022)])

dados <- rbind(dados2020,dados2021,dados2022)
dados <- dados[!is.na(dados$Cook15),]
dados <- dados[!is.na(dados$Cook20),]
dados <- dados[!is.na(dados$Cook25),]
dados <- dados[!is.na(dados$Cook30),]
dados <- dados[!is.na(dados$Cook40),]
dados <- droplevels(dados)

dados$Cook15 <- as.factor(dados$Cook15)
dados$Cook20 <- as.factor(dados$Cook20)
dados$Cook25 <- as.factor(dados$Cook25)
dados$Cook30 <- as.factor(dados$Cook30)
dados$Cook40 <- as.factor(dados$Cook40)

levels(dados$Cook15) <- c("No","No","Yes","Yes")
levels(dados$Cook20) <- c("No","No","Yes","Yes")
levels(dados$Cook25) <- c("No","No","Yes","Yes")
levels(dados$Cook30) <- c("No","No","Yes","Yes")
levels(dados$Cook40) <- c("No","No","Yes","Yes")
  
dados$accession_name <- as.factor(dados$accession_name)
dados$accession_name <- recode(dados$accession_name, 
                               # "EucxRox" = "EucaliptoXRoxinha", 
                                "BRS-GemaOvo" = "BRS-Gema-de-Ovo",
                                "Aipim-Brasil" = "Aipim Brasil",
                                "Aipim-Abacate" = "AipimAbacate")  
```

### creating multi classes trait BUCHI
```{r, eval = F}
dados1 <- dados[,Cooking_traits]
dados1$Cook15 <- gsub("Yes","15min",dados1$Cook15)
dados1$Cook20 <- gsub("Yes","20min",dados1$Cook20)
dados1$Cook25 <- gsub("Yes","25min",dados1$Cook25)
dados1$Cook30 <- gsub("Yes","30min",dados1$Cook30)
dados1$Cook40 <- gsub("Yes","40min",dados1$Cook40)
dados1$Mult6C <- as.factor(str_c(dados1$Cook15,dados1$Cook20,dados1$Cook25,
                                 dados1$Cook30,dados1$Cook40,sep = "",
                                 collapse = NULL))
levels(dados1$Mult6C) <- c("15min","15min","20min","25min","30min","40min","No")
dados1$Mult4C <- dados1$Mult6C
levels(dados1$Mult4C) <- c("15min","25min","25min","40min","40min","No")
dados <- cbind(dados[,1:10],dados1[,6:7],dados[,11:ncol(dados)])
```


### Save data BUCHI
```{r}
#save(dados, file = here::here("output", "dadosBUCHI.RData"))
```


## Dados SCIO
```{r, eval = F}
dados2022<-read.table(file=here::here("data","2022_DadosNIRSCIO_Cook.txt"), 
                      header=T, sep="\t", na.strings="NA",
                      strip.white=TRUE, check.names=FALSE)
dados2022 <- cbind(dados2022[,c("Trial","plot_name",
                                "accession_name",
                                "plot_number",
                                "block_number",
                                Cooking_traits,"Type")],
                                dados2022[12:ncol(dados2022)])

dados <- dados2022
dados <- dados[!is.na(dados$Cook15),]
dados <- dados[!is.na(dados$Cook20),]
dados <- dados[!is.na(dados$Cook25),]
dados <- dados[!is.na(dados$Cook30),]
dados <- dados[!is.na(dados$Cook40),]
dados <- droplevels(dados)

dados$Cook15 <- as.factor(dados$Cook15)
dados$Cook20 <- as.factor(dados$Cook20)
dados$Cook25 <- as.factor(dados$Cook25)
dados$Cook30 <- as.factor(dados$Cook30)
dados$Cook40 <- as.factor(dados$Cook40)

#levels(dados$Cook15) <- c("No","No","Yes","Yes")
#levels(dados$Cook20) <- c("No","No","Yes","Yes")
#levels(dados$Cook25) <- c("No","No","Yes","Yes")
#levels(dados$Cook30) <- c("No","No","Yes","Yes")
#levels(dados$Cook40) <- c("No","No","Yes","Yes")
  
dados$accession_name <- as.factor(dados$accession_name)
levels(as.factor(dados$accession_name))  

dados$accession_name <- recode(dados$accession_name, 
                               # "EucxRox" = "EucaliptoXRoxinha", 
                                "BRS-GemaOvo" = "BRS-Gema-de-Ovo")  

dados$Type <- as.factor(dados$Type)
levels(as.factor(dados$Type))  
levels(dados$Type) <- c("Fresh Root","Mashed","Mashed")
```


### creating multi classes trait SCIO
```{r, eval = F}
dados1 <- dados[,Cooking_traits]
dados1$Cook15 <- gsub("Yes","15min",dados1$Cook15)
dados1$Cook20 <- gsub("Yes","20min",dados1$Cook20)
dados1$Cook25 <- gsub("Yes","25min",dados1$Cook25)
dados1$Cook30 <- gsub("Yes","30min",dados1$Cook30)
dados1$Cook40 <- gsub("Yes","40min",dados1$Cook40)
dados1$Mult6C <- as.factor(str_c(dados1$Cook15,dados1$Cook20,dados1$Cook25,
                                 dados1$Cook30,dados1$Cook40,sep = "",
                                 collapse = NULL))
levels(dados1$Mult6C) <- c("15min","20min","25min","30min","40min","No")
dados1$Mult4C <- dados1$Mult6C
levels(dados1$Mult4C) <- c("15min","25min","25min","40min","40min","No")
dados <- cbind(dados[,1:10],dados1[,6:7],dados[,11:ncol(dados)])
```


### SAVE DATA SCIO
```{r}

#save(dados, file = here::here("output", "dadosSCIO.RData"))

```

